### ISSUE TITLE
Error on m1 mac

### ISSUE THREAD

**Issue by janu8ry** [comp500/ScreenshotToClipboard#23]
[IO-Worker-16/ERROR]: Caught exception in thread Thread[IO-Worker-16,10,main]
java.lang.NoClassDefFoundError: Could not initialize class ca.weblite.objc.RuntimeUtils
	at ca.weblite.objc.Client.sendProxy(Client.java:369) ~[java-objc-bridge-1.0.0.jar:?]
	at link.infra.screenshotclipboard.MacOSCompat.doCopyMacOS(MacOSCompat.java:22) ~[screenshot-to-clipboard-1.0.7-fabric.jar:?]
	at net.minecraft.class_318.handler$bcb000$screenshotCapturedMac(class_318.java:1020) ~[client-intermediary.jar:?]
	at net.minecraft.class_318.method_1661(class_318.java:69) ~[client-intermediary.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by comp500** [comment]
What are you using to run the game on M1? Looks like it doesn't set up the java-objc-bridge library properly, you'll probably find that the in-game narrator option is broken too.

**Comment by janu8ry** [comment]
I'm using multiMC and https://github.com/yusefnapora/m1-multimc-hack to run minecraft.

**Comment by comp500** [comment]
It's an issue with m1-multimc-hack, see https://github.com/yusefnapora/m1-multimc-hack/issues/32#issuecomment-1019664729
