### ISSUE TITLE
Mod doesn't work with ViaFabric installed

### ISSUE THREAD

**Issue by cs127** [comp500/ScreenshotToClipboard#8]
When ViaFabric and ViaVersion are installed in the mods folder, the mod will not copy the screenshots to the clipboard.
In the latest.log file, it shows this:

```
[22:15:00] [Screenshot to Clipboard Copy/INFO]: [STDERR]: java.awt.HeadlessException
[22:15:00] [Screenshot to Clipboard Copy/INFO]: [STDERR]: 	at sun.awt.HeadlessToolkit.getSystemClipboard(HeadlessToolkit.java:309)
[22:15:00] [Screenshot to Clipboard Copy/INFO]: [STDERR]: 	at link.infra.screenshotclipboard.ScreenshotToClipboard.lambda$doCopy$0(ScreenshotToClipboard.java:103)
[22:15:00] [Screenshot to Clipboard Copy/INFO]: [STDERR]: 	at link.infra.screenshotclipboard.ScreenshotToClipboard$$Lambda$7097/1185271322.run(Unknown Source)
[22:15:00] [Screenshot to Clipboard Copy/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:745)
```

Minecraft version: 1.16.1
Fabric loader version: 0.9.0 build 204
Fabric API version: 0.16.0 build 384
ViaFabric version: 0.2.5 snapshot build 343.1
ViaVersion version: 3.0.2 snapshot build 432

ViaFabric:
https://github.com/ViaVersion/ViaFabric

ViaVersion:
https://ci.viaversion.com/job/ViaVersion/
https://github.com/ViaVersion/ViaVersion

**Comment by comp500** [comment]
Fixed in c9f2280
